#!/usr/bin/env bash
# Scans a generated project directory (and optionally a commit message file)
# for AI-attribution strings that must never appear in pushed output.
# Usage: attribution-scan.sh <project-dir> [commit-message-file]
set -euo pipefail

PROJECT_DIR="${1:-}"
COMMIT_MSG_FILE="${2:-}"

if [[ -z "$PROJECT_DIR" || ! -d "$PROJECT_DIR" ]]; then
  echo "attribution-scan: missing or invalid project directory: '$PROJECT_DIR'" >&2
  exit 1
fi

# Case-insensitive substrings. Phrases, not bare tool/vendor names, so that
# legitimate technical references (e.g. a linter that processes files named
# CLAUDE.md) don't false-flag. "anthropic" stays bare since it has no
# plausible non-attribution use in a generated project.
PATTERNS=(
  "anthropic"
  "ai-generated"
  "ai generated"
  "generated with ai"
  "generated by ai"
  "written by ai"
  "chatgpt"
  "openai"
  "built with claude"
  "built using claude"
  "made with claude"
  "made using claude"
  "generated by claude"
  "generated with claude"
  "written by claude"
  "claude code"
  "co-authored-by: claude"
  "co-authored by claude"
  "powered by claude"
)

FOUND=0

for pattern in "${PATTERNS[@]}"; do
  matches=$(grep -RIn --exclude-dir=.git -i -- "$pattern" "$PROJECT_DIR" || true)
  if [[ -n "$matches" ]]; then
    echo "attribution-scan: found pattern '$pattern' in:" >&2
    echo "$matches" >&2
    FOUND=1
  fi
done

if [[ -n "$COMMIT_MSG_FILE" && -f "$COMMIT_MSG_FILE" ]]; then
  for pattern in "${PATTERNS[@]}"; do
    if grep -in -- "$pattern" "$COMMIT_MSG_FILE" >/dev/null; then
      echo "attribution-scan: found pattern '$pattern' in commit message file" >&2
      FOUND=1
    fi
  done
fi

if [[ "$FOUND" -eq 1 ]]; then
  echo "attribution-scan: FAIL — AI attribution references found" >&2
  exit 1
fi

echo "attribution-scan: PASS — no AI attribution references found"
exit 0
