#!/usr/bin/env bash
# Scans a generated project directory (and optionally a commit message file)
# for AI-attribution strings that must never appear in pushed output.
# Usage: attribution-scan.sh <project-dir> [commit-message-file]
set -euo pipefail

PROJECT_DIR="${1:-}"
COMMIT_MSG_FILE="${2:-}"

if [[ -z "$PROJECT_DIR" || ! -d "$PROJECT_DIR" ]]; then
  echo "attribution-scan: missing or invalid project directory: '$PROJECT_DIR'" >&2
  exit 1
fi

# Case-insensitive, word-ish boundaries where sensible. Kept as plain
# substrings to err on the side of catching more, not less.
PATTERNS=(
  "claude"
  "anthropic"
  "ai-generated"
  "ai generated"
  "generated with ai"
  "generated by ai"
  "written by ai"
  "gpt-"
  "chatgpt"
  "openai"
  "co-authored-by: claude"
  "made with claude"
)

FOUND=0

for pattern in "${PATTERNS[@]}"; do
  matches=$(grep -RIn --exclude-dir=.git -i -- "$pattern" "$PROJECT_DIR" || true)
  if [[ -n "$matches" ]]; then
    echo "attribution-scan: found pattern '$pattern' in:" >&2
    echo "$matches" >&2
    FOUND=1
  fi
done

if [[ -n "$COMMIT_MSG_FILE" && -f "$COMMIT_MSG_FILE" ]]; then
  for pattern in "${PATTERNS[@]}"; do
    if grep -in -- "$pattern" "$COMMIT_MSG_FILE" >/dev/null; then
      echo "attribution-scan: found pattern '$pattern' in commit message file" >&2
      FOUND=1
    fi
  done
fi

if [[ "$FOUND" -eq 1 ]]; then
  echo "attribution-scan: FAIL — AI attribution references found" >&2
  exit 1
fi

echo "attribution-scan: PASS — no AI attribution references found"
exit 0
